// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
)

type School struct {
	ID        int32
	Name      string
	Type      string
	Logo      string
	Createdat sql.NullTime
	Updatedat sql.NullTime
}
